import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const routes = [
  { href: "/about",name:"About us" },
  { href: "/contact",name:"Contact us" },
  { href: "/loading_error",name:"Loading Error" },
  { href: "/dynamic_routes",name:"Dynamic Routes" },
  { href: "/cache",name:"Caching" },
  { href: "/ssg",name:"Static Site Generation" },
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul>
          {routes.map((item) => {
            return (
              <li key={item.href}>
                <Link href={item.href}>{item.name}</Link>
              </li>
            );
          })}
        </ul>
        {children}
      </body>
    </html>
  );
}
